version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: root
      MYSQL_PASSWORD: roor
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
