version: "3"

networks:
  internal:

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
     - "8080:87"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d  
      - ./data/log:/var/logs/nginx/      
    depends_on:
      - mysql
    networks:
      - internal
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    networks:
     - internal